#!/bin/bash

# =============================================================================
# Script: generate_and_upload_context.sh
# Description: Generates a comprehensive project context file and uploads it
#              to a file sharing service.
# Author: Generated by AI
# Date: $(date +%Y-%m-%d)
# =============================================================================

# -----------------------------------------------------------------------------
# Function: print_error
# Purpose:  Print error messages with a clear prefix
# Arguments: $1 - Error message to display
# -----------------------------------------------------------------------------
print_error() {
    echo "❌ Error: $1" >&2
}

# -----------------------------------------------------------------------------
# Function: print_success
# Purpose:  Print success messages with a clear prefix
# Arguments: $1 - Success message to display
# -----------------------------------------------------------------------------
print_success() {
    echo "✅ $1"
}

# -----------------------------------------------------------------------------
# Function: print_info
# Purpose:  Print informational messages
# Arguments: $1 - Info message to display
# -----------------------------------------------------------------------------
print_info() {
    echo "ℹ️  $1"
}

# -----------------------------------------------------------------------------
# Function: print_warning
# Purpose:  Print warning messages
# Arguments: $1 - Warning message to display
# -----------------------------------------------------------------------------
print_warning() {
    echo "⚠️  Warning: $1" >&2
}

# -----------------------------------------------------------------------------
# Main Script Execution
# -----------------------------------------------------------------------------

# Check for required dependencies
print_info "Checking dependencies..."

# Ensure python3 is installed
if ! command -v python3 >/dev/null 2>&1; then
    print_error "python3 is required but not installed. Please install Python 3.6+ and try again."
    exit 1
fi

# Ensure curl is installed for uploading
if ! command -v curl >/dev/null 2>&1; then
    print_error "curl is required for uploading but not installed. Please install curl and try again."
    exit 1
fi

# Verify Python version is at least 3.6
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
if ! python3 -c "import sys; exit(0 if sys.version_info >= (3, 6) else 1)"; then
    print_error "Python 3.6+ is required. Found version $PYTHON_VERSION"
    exit 1
fi

print_success "All dependencies satisfied"

# Generate a 10-character random alphanumeric string for the filename
# Uses /dev/urandom for cryptographically secure randomness
RANDOM_NAME=$(LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom 2>/dev/null | head -c 10)
if [ -z "$RANDOM_NAME" ]; then
    # Fallback to date-based naming if /dev/urandom fails
    RANDOM_NAME=$(date +%s | sha256sum | base64 | head -c 10 | tr -d '/+' | tr '+' 'a' | tr '/' 'A')
fi
OUTPUT_FILE="${RANDOM_NAME}.txt"

print_info "Gathering context into ${OUTPUT_FILE}..."

# -----------------------------------------------------------------------------
# Python Script Section
# Purpose: Collects system information, file tree, and file contents
# Encoding: Explicitly uses UTF-8 for all I/O operations
# -----------------------------------------------------------------------------
python3 - "$OUTPUT_FILE" <<'EOF'
import os
import sys
import platform
from pathlib import Path

# ============================================================================
# Configuration Constants
# ============================================================================

OUTPUT_FILE = sys.argv[1]  # Get output filename from command line argument

# Directories to ignore during traversal
IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", "venv", ".venv", "env", ".env",
    "dist", "build", ".idea", ".vscode", ".next", "out", "bin", "obj", ".github",
    ".pytest_cache", ".mypy_cache", ".tox", "htmlcov", ".coverage"
}

# File extensions to ignore
IGNORE_EXTS = {
    ".pyc", ".pyo", ".pyd", ".db", ".sqlite", ".png", ".jpg", ".jpeg", ".gif",
    ".ico", ".svg", ".zip", ".tar", ".gz", ".pdf", ".exe", ".dll", ".so", ".dylib",
    ".bin", ".dat", ".log", ".lock", ".context.txt", OUTPUT_FILE
}

# Maximum file size to read (1 MB)
MAX_FILE_SIZE = 1024 * 1024

# ----------------------------------------------------------------------------
# Function: system_info
# Purpose:  Gather system information
# Returns:  List of strings containing system information
# ----------------------------------------------------------------------------
def system_info():
    """Collect system information for debugging purposes."""
    return [
        f"Operating System: {platform.system()} {platform.release()}",
        f"OS Version: {platform.version()}",
        f"Python Version: {sys.version.split()[0]}",
        f"Python Executable: {sys.executable}",
        f"CPU Cores: {os.cpu_count()}",
        f"Current Working Directory: {os.getcwd()}",
        f"File System Encoding: {sys.getfilesystemencoding()}",
        f"Default Encoding: {sys.getdefaultencoding()}"
    ]

# ----------------------------------------------------------------------------
# Function: generate_tree
# Purpose:  Generate a visual directory tree from a list of file paths
# Arguments: paths - List of relative file paths
# Returns:   String containing the ASCII tree representation
# ----------------------------------------------------------------------------
def generate_tree(paths):
    """Generate an ASCII directory tree from a list of file paths."""
    tree = {}
    
    # Build tree structure
    for path in paths:
        parts = path.split("/")
        cur = tree
        for i, p in enumerate(parts):
            if p not in cur:
                cur[p] = {} if i < len(parts) - 1 else None
            if cur[p] is not None:
                cur = cur[p]
            else:
                break
    
    # Render tree recursively
    def render(node, prefix=""):
        out = ""
        if not node or node is None:
            return out
        keys = sorted(node.keys())
        for i, k in enumerate(keys):
            last = i == len(keys) - 1
            out += prefix + ("└── " if last else "├── ") + k + "\n"
            if isinstance(node[k], dict) and node[k] is not None:
                out += render(node[k], prefix + ("    " if last else "│   "))
        return out
    
    return render(tree)

# ----------------------------------------------------------------------------
# Function: read_file_safely
# Purpose:  Read a file with proper UTF-8 encoding handling
# Arguments: filepath - Path to the file to read
# Returns:   Tuple (success: bool, content: str)
# ----------------------------------------------------------------------------
def read_file_safely(filepath):
    """
    Read a file safely with UTF-8 encoding.
    Falls back to latin-1 if UTF-8 fails.
    """
    # Try UTF-8 first (most common and preferred)
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return True, f.read()
    except UnicodeDecodeError:
        # If UTF-8 fails, try with error handling
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
                return True, f"# WARNING: File contained invalid UTF-8 characters\n# Replaced with '�' symbol\n\n{content}"
        except Exception as e:
            # Fallback to latin-1 which can read any byte
            try:
                with open(filepath, "r", encoding="latin-1") as f:
                    content = f.read()
                    return True, f"# WARNING: File encoded in {sys.getfilesystemencoding()}, converted from latin-1\n\n{content}"
            except Exception as e:
                return False, f"# ERROR: Could not read file: {str(e)}"
    except Exception as e:
        return False, f"# ERROR: {str(e)}"

# ----------------------------------------------------------------------------
# Main collection process
# ----------------------------------------------------------------------------

print(f"Scanning directory: {os.getcwd()}", file=sys.stderr)
print(f"Using UTF-8 encoding for output", file=sys.stderr)

files = []
paths = []

# Walk through directory structure
for root, dirs, fs in os.walk("."):
    # Filter out ignored directories
    dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
    
    for f in fs:
        # Skip files with ignored extensions
        if any(f.endswith(ext) for ext in IGNORE_EXTS):
            continue
        
        path = os.path.join(root, f)
        abs_path = os.path.abspath(path)
        rel_path = os.path.relpath(path, ".")
        
        # Skip files that are too large
        try:
            if os.path.getsize(path) > MAX_FILE_SIZE:
                print(f"  Skipping large file: {rel_path}", file=sys.stderr)
                continue
        except OSError:
            continue
        
        # Read file content with proper encoding handling
        success, content = read_file_safely(path)
        
        if success:
            files.append({
                "path": rel_path,
                "absolute_path": abs_path,
                "content": content
            })
            paths.append(rel_path)

print(f"Collected {len(files)} files", file=sys.stderr)

# ----------------------------------------------------------------------------
# Build output content
# ----------------------------------------------------------------------------

out = []

# System Information Section
out.append("=" * 80)
out.append("SYSTEM INFORMATION")
out.append("=" * 80)
out.extend(system_info())
out.append("")
out.append("# Note: This file uses UTF-8 encoding")
out.append("")

# File Tree Section
out.append("=" * 80)
out.append("FILE TREE")
out.append("=" * 80)
out.append("")
out.append(generate_tree(paths))
out.append("")

# File Contents Section
out.append("=" * 80)
out.append("FILE CONTENTS")
out.append("=" * 80)
out.append("")

# Add each file's content
for f in files:
    out.append("=" * 80)
    out.append(f"Path: {f['absolute_path']}")
    out.append(f"Relative Path: {f['path']}")
    out.append("=" * 80)
    out.append(f["content"])
    out.append("")  # Add empty line between files

# Write output file with UTF-8 encoding
try:
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"✅ Successfully wrote {len(files)} files to {os.path.abspath(OUTPUT_FILE)}", file=sys.stderr)
except IOError as e:
    print(f"❌ Error writing file: {e}", file=sys.stderr)
    sys.exit(1)

print(f"✅ Local file ready: {os.path.abspath(OUTPUT_FILE)}", file=sys.stderr)
EOF

# Capture Python script exit code
PYTHON_EXIT_CODE=$?
if [ $PYTHON_EXIT_CODE -ne 0 ]; then
    print_error "Python script failed with exit code $PYTHON_EXIT_CODE"
    exit 1
fi

# Ensure the file was created successfully before attempting an upload
if [ ! -f "$OUTPUT_FILE" ]; then
    print_error "Failed to generate $OUTPUT_FILE"
    exit 1
fi

# Display file size for verification
FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
print_info "Generated file size: $FILE_SIZE"

print_info "Uploading ${OUTPUT_FILE} to files.imeow.ir..."

# -----------------------------------------------------------------------------
# Upload with curl
# -----------------------------------------------------------------------------
# Execute the upload request with curl
# -s for silent mode (no progress meter)
# -X POST for HTTP POST method
# -H for custom headers
# -F for form data (multipart/form-data)
RESPONSE=$(curl -s -X POST \
  -H "Referrer-Policy: strict-origin-when-cross-origin" \
  -H "Accept: application/json" \
  -F "file=@${OUTPUT_FILE}" \
  -F "bucket=default" \
  https://files.imeow.ir/upload 2>&1)

CURL_EXIT_CODE=$?

if [ $CURL_EXIT_CODE -ne 0 ]; then
    print_error "curl command failed with exit code $CURL_EXIT_CODE"
    print_error "Please check your network connection and try again"
    exit 1
fi

# Check if response is empty
if [ -z "$RESPONSE" ]; then
    print_error "Received empty response from server"
    exit 1
fi

# -----------------------------------------------------------------------------
# Parse JSON response safely using Python
# -----------------------------------------------------------------------------
# Extract success field
SUCCESS=$(python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    success = data.get('success', False)
    print(success)
except json.JSONDecodeError as e:
    print('false')
    sys.stderr.write(f'JSON Parse Error: {e}\n')
except Exception as e:
    print('false')
    sys.stderr.write(f'Error: {e}\n')
" <<< "$RESPONSE" 2>/dev/null)

# Extract download URL if successful
if [ "$SUCCESS" = "True" ] || [ "$SUCCESS" = "true" ]; then
    DOWNLOAD_PATH=$(python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    url = data.get('download_url', '')
    print(url)
except:
    print('')
" <<< "$RESPONSE" 2>/dev/null)
    
    FULL_URL="https://files.imeow.ir${DOWNLOAD_PATH}"
    
    echo ""
    echo "============================================================"
    print_success "Upload Successful!"
    echo "🔗 Download URL: ${FULL_URL}"
    echo "📁 Local file: $(pwd)/${OUTPUT_FILE}"
    echo "📊 File size: ${FILE_SIZE}"
    echo "============================================================"
    echo ""
    
    # Optional: Copy URL to clipboard if possible
    if command -v pbcopy >/dev/null 2>&1; then
        echo -n "$FULL_URL" | pbcopy
        print_info "URL copied to clipboard (macOS)"
    elif command -v xclip >/dev/null 2>&1; then
        echo -n "$FULL_URL" | xclip -selection clipboard
        print_info "URL copied to clipboard (Linux)"
    elif command -v clip.exe >/dev/null 2>&1; then
        echo -n "$FULL_URL" | clip.exe
        print_info "URL copied to clipboard (Windows)"
    fi
else
    echo ""
    echo "============================================================"
    print_error "Upload Failed!"
    echo "   Server Response: $RESPONSE"
    echo "============================================================"
    echo ""
    
    # Try to extract error message if JSON
    ERROR_MSG=$(python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    error = data.get('error', data.get('message', 'Unknown error'))
    print(error)
except:
    print('Unable to parse error message')
" <<< "$RESPONSE" 2>/dev/null)
    
    if [ -n "$ERROR_MSG" ]; then
        print_error "Server message: $ERROR_MSG"
    fi
    
    exit 1
fi

# Clean up local file? Uncomment if you want to delete after upload
# print_info "Cleaning up local file..."
# rm -f "$OUTPUT_FILE"
# print_success "Cleanup complete"

exit 0
